env:
  global:
   - secure: "iT17ZEsnp4jdHQS0NUT6B60ntgVEQKmDS8gr/eghfdKtuTpTWRy0d+w1R4RZX+5dYG6jtW06HYCKuuVfZ4S5ExqyADQ+XZK6CtXQfgCAAEFRuOW1VjojdAwoJIOiyShg72BLDl0z9fGg9xrJtXHue05h7F7hklHOahOKgP3h5rVnil76XGEygXVPVeLJVOujJeNhRN7Fe54S4aifLbfV8bojn3VL61vkz/JAptcQ/41NcVGZRXlxeh7hz30OHOibJUQJWK8irO5zKVflL7gtdoDm9Be+XAm96YHqoPaRY0vx05rcEgfU72ss0mMU8qdyLFmGvbHIbglXeP+wrbUcKa7vjNyKHIiBkUvDMK5kUEHRKK2LjakOum178JIvnGrTNGo5tkbRfv0jTYpbY6B2cuz4mcz6sDk6I0420lXWErtwjmEopsBQvUiq1s4i6Nm/rXOIdHNr26upT1eWUAlV5o5vgSGZWk+JMKXh3RjABgByEOb39Be5/b0z23PUQg39QC1S+jQArom/GKGOYU9jziWuUsggox+POhfoXUkcbU2kyq3+Oof/iS045HDBpugo51VwU81VqEzS54lf7eD7RkN1RsTKv5ZYJnjGXvOLMSJjryRKVToaMJJYXCT1g6N0EPk6LMG/VBhDUvCXzk9Z4gOmZLhz9oWoPwLVkzh2+6o="

install:
 - true

script:
 - true

after_script:
 - ls -alrt
 - ./deploy.sh

notifications:
  email: false
